version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  vectordb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - vectordb_data:/chroma/data

volumes:
  vectordb_data:

networks:
  app-network:
    driver: bridge 